/**
 * D1 Database Schema
 * Run via: npx wrangler d1 migrations apply cashclaw-db --local
 */

import { SQL_TABLES } from './schema-tables';
import { SQL_INDEXES } from './schema-indexes';

export const SQL = {
  ...SQL_TABLES,
  ...SQL_INDEXES,
};

export const MIGRATION = `
${SQL.CREATE_USERS};
${SQL.CREATE_BOTS};
${SQL.CREATE_TRADES};
${SQL.CREATE_CREDENTIALS};
${SQL.CREATE_TRADE_EVENTS};
${SQL.CREATE_CAPITAL_SNAPSHOTS};
${SQL.CREATE_AUDIT_LOG};
${SQL.CREATE_AUDIT_LEDGER};
${SQL.CREATE_INDEX_AUDIT_LEDGER_CREATED};
${SQL.CREATE_BACKTEST_RESULTS};
${SQL.CREATE_INDEX_USER_AUDIT};
${SQL.CREATE_INDEX_BOT_AUDIT};
${SQL.CREATE_INDEX_BOT_USER};
${SQL.CREATE_INDEX_TRADES_BOT};
${SQL.CREATE_INDEX_EVENTS_BOT_TIME};
${SQL.CREATE_INDEX_SNAPSHOTS_BOT};
${SQL.CREATE_INDEX_BACKTEST_BOT};
${SQL.CREATE_CIRCUIT_BREAKER};
`;
