// Zoo Phase 3 seed falsification — MANUAL ONLY. Run:
//   npx tsx scripts/zoo-phase3-falsify.ts
// Paper/backtest only; no orders. Deterministic seeds (FNV-1a32). No
// fabricated numbers: thin data overlap or missing symbols exits non-zero
// (BLOCKED), mirroring scripts/rv-pairs-verdict.ts.
//
// Loads the cached Binance 1d panels (BTCUSDT/ETHUSDT/SOLUSDT, 730 aligned
// bars), imports the committed phase-2 seed manifest with ALL zoo market
// tags mapped to the crypto universe (documented adaptation — Phase 2 D4
// precedent), runs the forest-layer falsification bridge, and writes a
// committed JSON artifact plus a human-readable markdown report.

import { loadCandles } from '@/forest/backtest/ohlcv-cache';
import { PHASE2_SEED_MANIFEST } from '@/tree/research/alpha/zoo/seeds/seed-manifest';
import {
  buildCryptoUniverse,
  buildSeedAdapterConfig,
  dataWindowFromPanels,
  panelFromCandles,
  type RawCandle,
  ZOO_SEED_SYMBOLS,
} from '@/forest/research/zoo-falsification/zoo-phase3-config';
import { runZooFalsification } from '@/forest/research/zoo-falsification/run-zoo-falsification';
import { validateAlignedPanels, type SymbolPanel } from '@/tree/alpha/factors';
import type { ZooFalsificationReport } from '@/forest/research/zoo-falsification/report-types';
import * as fs from 'node:fs';
import * as path from 'node:path';

const CACHE_KEY = (s: string) => `binance:${s}:1d`;
const MIN_BARS = 730;
const REPORT_DIR = 'plans/reports';
const REPORT_JSON = 'zoo-phase3-falsification-report.json';
const REPORT_MD = 'docs/zoo-seed-falsification-report.md';

/** Load + align the three cached 1d panels; fail closed on missing/thin data. */
function loadPanels(): SymbolPanel[] {
  const panels: SymbolPanel[] = [];
  for (const symbol of ZOO_SEED_SYMBOLS) {
    const loaded = loadCandles(CACHE_KEY(symbol));
    if (!loaded || loaded.candles.length < MIN_BARS) {
      throw new Error(`BLOCKED: ${symbol} missing/thin (${loaded?.candles.length ?? 0} bars < ${MIN_BARS})`);
    }
    panels.push(panelFromCandles(symbol, loaded.candles as readonly RawCandle[]));
  }
  validateAlignedPanels(panels);
  return panels;
}

function writeJson(name: string, payload: unknown): void {
  fs.mkdirSync(REPORT_DIR, { recursive: true });
  fs.writeFileSync(path.join(REPORT_DIR, name), JSON.stringify(payload, null, 2));
}

function writeMd(report: ZooFalsificationReport): void {
  const lines: string[] = [];
  lines.push('# Zoo Seed Falsification Report — Phase 3');
  lines.push('');
  lines.push(`Generated by \`scripts/zoo-phase3-falsify.ts\` from the committed phase-2 seed manifest (${PHASE2_SEED_MANIFEST.sourceRepository} @ ${PHASE2_SEED_MANIFEST.sourceVersion}).`);
  lines.push('');
  lines.push('## External-validity caveat');
  lines.push('');
  lines.push('These alphas were designed for equity markets. This run executes them on a 3-symbol Binance crypto panel (BTCUSDT/ETHUSDT/SOLUSDT, 730 aligned daily bars, 2024-08-19 → 2026-08-18). The result is a **pipeline demonstration** — it proves the Vibe-proposes → CashClaw-falsifies loop runs end-to-end on real cached data — and is **not a tradable conclusion** for any market.');
  lines.push('');
  lines.push('## Totals');
  lines.push('');
  const t = report.totals;
  lines.push(`- Manifest entries: ${report.meta.manifestEntries}`);
  lines.push(`- Evaluated alive: ${t.evaluatedAlive}`);
  lines.push(`- Falsified: ${t.falsified}`);
  lines.push(`- Not evaluable: ${t.notEvaluable}`);
  lines.push(`- Skipped at import: ${t.skippedImport}`);
  lines.push(`- Bucket sum ≡ entries: ${t.evaluatedAlive + t.falsified + t.notEvaluable + t.skippedImport} ≡ ${report.meta.manifestEntries}`);
  lines.push('');
  lines.push('## Per-alpha verdicts');
  lines.push('');
  lines.push('| sourceAlphaId | verdict | reasons | icMean | icIR | validIc |');
  lines.push('|---|---|---|---|---|---|');
  for (const row of report.rows) {
    const ic = row.icStats;
    const icMean = ic?.icMean == null ? '—' : ic.icMean.toFixed(4);
    const icIr = ic?.icIr == null ? '—' : ic.icIr.toFixed(3);
    const validIc = ic == null ? '—' : String(ic.validIcCount);
    const reasons = row.reasons.join('; ').replace(/\|/g, '\\|');
    lines.push(`| ${row.sourceAlphaId} | ${row.verdict} | ${reasons} | ${icMean} | ${icIr} | ${validIc} |`);
  }
  lines.push('');
  lines.push('## Deferred checks (recorded, not run)');
  lines.push('');
  for (const dc of report.meta.deferredChecks) {
    lines.push(`- **${dc.check}**: ${dc.reason}`);
  }
  lines.push('');
  lines.push('## Caveats');
  lines.push('');
  for (const c of report.meta.caveats) lines.push(`- ${c}`);
  lines.push('');
  fs.writeFileSync(path.join(process.cwd(), REPORT_MD), lines.join('\n'));
}

async function main(): Promise<void> {
  const panels = loadPanels();
  const config = {
    adapterConfig: buildSeedAdapterConfig(dataWindowFromPanels(panels)),
  };
  const report = await runZooFalsification(PHASE2_SEED_MANIFEST, panels, config);
  writeJson(REPORT_JSON, report);
  writeMd(report);
  console.log(
    `zoo seed falsification: alive=${report.totals.evaluatedAlive} falsified=${report.totals.falsified} ` +
      `not_evaluable=${report.totals.notEvaluable} skipped=${report.totals.skippedImport} ` +
      `total=${report.totals.total} (Σ≡${report.meta.manifestEntries})`,
  );
}

main().catch((err: unknown) => {
  console.error(err instanceof Error ? err.message : String(err));
  process.exit(1);
});