// Multiple-Testing Defense — Permutation Test + Random-Entry Comparison
// Two defenses against "the strategy is just luck":
// 1. `permutationTest` shuffles the return<->signal alignment to build a
//    null distribution of the statistic; a real edge must beat it.
// 2. `compareAgainstRandomEntry` compares the strategy's EvaluationReport
//    against a `random_entry` baseline report (generated by
//    baselines/runner.ts — reused, never rebuilt here).
// Pure and deterministic: shuffle order is fully determined by the seed.

import type { EvaluationReport } from '@/forest/alpha/evaluation/report';
import { mulberry32, shuffleInPlace } from './seeded-prng';
import type {
  PermutationOptions,
  PermutationTestResult,
  RandomEntryComparisonOptions,
  RandomEntryVerdict,
} from './types';
import type { StatFn } from './bootstrap';

function validatePermutationInput(
  strategyReturns: readonly number[],
  entrySignals: readonly number[],
  options: PermutationOptions,
): void {
  if (strategyReturns.length < 2) {
    throw new Error(
      `permutationTest requires at least 2 returns, got ${strategyReturns.length}`,
    );
  }
  if (strategyReturns.length !== entrySignals.length) {
    throw new Error(
      `permutationTest requires aligned arrays: ${strategyReturns.length} returns vs ${entrySignals.length} signals`,
    );
  }
  if (!Number.isInteger(options.iterations) || options.iterations < 1) {
    throw new Error(
      `permutationTest requires iterations >= 1, got ${options.iterations}`,
    );
  }
  if (!Number.isFinite(options.seed)) {
    throw new Error('permutationTest requires a finite numeric seed');
  }
}

/** Element-wise alignment of returns with signals (position-weighted). */
function alignedSeries(
  strategyReturns: readonly number[],
  signals: readonly number[],
): number[] {
  return strategyReturns.map((r, i) => r * signals[i]);
}

/**
 * Permutation test of the return<->signal alignment.
 *
 * The observed statistic is computed on the aligned series
 * (returns x signals). Each permutation shuffles the signal alignment
 * (Fisher–Yates, seeded) and recomputes the statistic on the broken
 * alignment. `pValue` is the fraction of permutations whose statistic is
 * >= the observed one (fail-closed: ties count against the strategy, so
 * an indistinguishable strategy yields pValue near 1).
 */
export function permutationTest(
  strategyReturns: readonly number[],
  entrySignals: readonly number[],
  statFn: StatFn,
  options: PermutationOptions,
): PermutationTestResult {
  validatePermutationInput(strategyReturns, entrySignals, options);

  const observed = statFn(alignedSeries(strategyReturns, entrySignals));
  if (!Number.isFinite(observed)) {
    throw new Error('permutationTest statistic returned a non-finite value');
  }

  const rng = mulberry32(options.seed);
  const shuffled = [...entrySignals];
  let sum = 0;
  let sumSq = 0;
  let atLeastObserved = 0;

  for (let iter = 0; iter < options.iterations; iter++) {
    shuffleInPlace(shuffled, rng);
    const stat = statFn(alignedSeries(strategyReturns, shuffled));
    sum += stat;
    sumSq += stat * stat;
    if (stat >= observed) atLeastObserved += 1;
  }

  const nullMean = sum / options.iterations;
  const variance = Math.max(sumSq / options.iterations - nullMean * nullMean, 0);

  return {
    observed,
    nullMean,
    nullStd: Math.sqrt(variance),
    pValue: atLeastObserved / options.iterations,
    iterations: options.iterations,
  };
}

/**
 * Compare a strategy report against a `random_entry` baseline report.
 *
 * The strategy must beat the baseline on expectancy net of costs by at
 * least `minEdge` (default 0). Expectancy in EvaluationReport is already
 * net of costs (fees/slippage deducted per trade). A strategy that is
 * indistinguishable from random entry FAILS — never a silent pass.
 */
export function compareAgainstRandomEntry(
  report: EvaluationReport,
  baselineReport: EvaluationReport,
  options: RandomEntryComparisonOptions = {},
): RandomEntryVerdict {
  const minEdge = options.minEdge ?? 0;
  if (!Number.isFinite(minEdge)) {
    throw new Error('compareAgainstRandomEntry requires a finite minEdge');
  }
  if (!Number.isFinite(report.expectancy)) {
    throw new Error('Strategy report expectancy must be finite');
  }
  if (!Number.isFinite(baselineReport.expectancy)) {
    throw new Error('Baseline report expectancy must be finite');
  }
  const edge = report.expectancy - baselineReport.expectancy;
  if (edge > minEdge) {
    return {
      passes: true,
      reason: `strategy expectancy exceeds random_entry by ${edge.toFixed(6)}`,
    };
  }
  return {
    passes: false,
    reason: `strategy expectancy edge over random_entry is ${edge.toFixed(6)} (required > ${minEdge})`,
  };
}
