// Multiple-Testing Defense — Permutation Test + Random-Entry Comparison
// Two defenses against "the strategy is just luck":
// 1. `permutationTest` shuffles the return<->signal alignment to build a
//    null distribution of the statistic; a real edge must beat it.
// 2. `compareAgainstRandomEntry` compares the strategy's EvaluationReport
//    against a `random_entry` baseline report (generated by
//    baselines/runner.ts — reused, never rebuilt here).
// Pure and deterministic: shuffle order is fully determined by the seed.

export { permutationTest } from './permutation-core';
export { compareAgainstRandomEntry } from './random-entry';
export type {
  PermutationOptions,
  PermutationTestResult,
  RandomEntryComparisonOptions,
  RandomEntryVerdict,
} from './types';
