// Multiple-Testing Defense — Random-Entry Comparison
// Compares the strategy's EvaluationReport against a `random_entry` baseline
// report (generated by baselines/runner.ts — reused, never rebuilt here).

import type { EvaluationReport } from '@/forest/alpha/evaluation/report';
import type { RandomEntryComparisonOptions, RandomEntryVerdict } from './types';

/**
 * Compare a strategy report against a `random_entry` baseline report.
 *
 * The strategy must beat the baseline on expectancy net of costs by at
 * least `minEdge` (default 0). Expectancy in EvaluationReport is already
 * net of costs (fees/slippage deducted per trade). A strategy that is
 * indistinguishable from random entry FAILS — never a silent pass.
 */
export function compareAgainstRandomEntry(
  report: EvaluationReport,
  baselineReport: EvaluationReport,
  options: RandomEntryComparisonOptions = {},
): RandomEntryVerdict {
  const minEdge = options.minEdge ?? 0;
  if (!Number.isFinite(minEdge)) {
    throw new Error('compareAgainstRandomEntry requires a finite minEdge');
  }
  if (!Number.isFinite(report.expectancy)) {
    throw new Error('Strategy report expectancy must be finite');
  }
  if (!Number.isFinite(baselineReport.expectancy)) {
    throw new Error('Baseline report expectancy must be finite');
  }
  const edge = report.expectancy - baselineReport.expectancy;
  if (edge > minEdge) {
    return {
      passes: true,
      reason: `strategy expectancy exceeds random_entry by ${edge.toFixed(6)}`,
    };
  }
  return {
    passes: false,
    reason: `strategy expectancy edge over random_entry is ${edge.toFixed(6)} (required > ${minEdge})`,
  };
}
